### ISSUE TITLE
Since 1.7, mark as read does no longer works for me

### ISSUE THREAD

**Issue by JulienPalard** [wallabag/android-app#55]
Since 1.7 (updated this morning), the "mark as read" buttun still returns to the list but the article does not disappear.

 - Nexus 5
 - Android 5.0

**Comment by tcitworld** [comment]
Should be fixed. Reopen if needed.

**Comment by JulienPalard** [comment]
This bug seems fixed bug the app has never been updated on the market )o: Still unusable (for me, everyone's usage different.).

**Comment by tcitworld** [comment]
You haven't got updated to version 1.8 ?

**Comment by JulienPalard** [comment]
I'm having the 1.8, since a long time, but still have this bug.

**Comment by tcitworld** [comment]
Do you observe the same this as me : returning to home screen (with the three buttons), then re-access the list does makes the item disappear.

**Comment by JulienPalard** [comment]
OK no longer got the bug today \o/ maybe I tested the wrong way last time, so it seems fixed in 1.8.
